import "@/styles/globals.css";
import { Nunito } from "next/font/google";
import { Provider } from "@/components/ThemeProvider";

//components
import Nav from "@/components/Nav";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <main className={`main ${nunito.className}`}>
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
