import "@/styles/globals.css";
import { Nunito } from "next/font/google";

//components
import Nav from "@/components/Nav";
import ProviderGroup from "@/components/ProviderGroup";

//hooks

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div id="screensizechecker">
          <div
            className="block sm:hidden m:hidden lg:hidden xl:hidden"
            data-size="xs"
          ></div>
          <div
            className="hidden sm-block m:hidden lg:hidden xl:hidden"
            data-size="sm"
          ></div>
          <div
            className="hidden sm:hidden m:block lg:hidden xl:hidden"
            data-size="md"
          ></div>
          <div
            className="hidden sm:hidden m:hidden lg:block xl:hidden"
            data-size="lg"
          ></div>
          <div
            className="hidden sm:hidden m:hidden lg:hidden xl:block"
            data-size="xl"
          ></div>
        </div>
        <ProviderGroup>
          <main className={`main ${nunito.className}`}>
            <Nav />
            {children}
          </main>
        </ProviderGroup>
      </body>
    </html>
  );
}

// export default storeWrapper.withRedux(RootLayout);
