import "@/styles/globals.css";
import { Nunito } from "next/font/google";

//components
import Nav from "@/components/Nav";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={`main ${nunito.className}`}>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
